# Generated by Django 5.2.6 on 2025-10-09 13:27
from django.utils import timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model
        
        User = get_user_model()

        if User.objects.exists():
            print("Superuser creation skipped: Users already exist.")
            return
        
        superuser = User.objects.create_superuser(
            username='karegowda',
            email='karegowdakn28@gmail.com',
            password='Kg@210798',
            last_login=timezone.now()
        )
        superuser.save()

    operations = [
        migrations.RunPython(create_superuser),
    ]
